# Site settings
title: "Posts"
email: patrickanthony@live.com
description: > # Welcome to my personal website dedicated to information
  about current and past projects of mine and tutorials on various technologies,
  services and application configurations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://patrickanth0ny.github.io" # the base hostname & protocol for your site
twitter_username: p_atrickanthony
github_username:  patrickanth0ny

# Build settings
markdown: kramdown
