# Site settings
title: Blog
email: patrickanthony@live.com
description: > # this means to ignore newlines until "baseurl:"
  Started a basic blog site using Jekyll to generate a basic static website.
  As time goes by the site will be updated more often and may become something
  less than basic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://patrickanth0ny.github.io" # the base hostname & protocol for your site
twitter_username: p_atrickanthony
github_username:  patrickanth0ny

# Build settings
markdown: kramdown
